### ISSUE TITLE
Suggestion: Transition to Object-Oriented Programming

### ISSUE THREAD

**Issue by nia-cloud-official** [TeghSinghJ/Live-Chatting-App#1]
Hi there,

I've been enjoying using this **Online Chatting System** and have noticed that the Codebase is primarily written in procedural PHP. I'd like to suggest transitioning to an object-oriented approach for several reasons...

Also, I noticed that the `.sql` file for setting up the `chatting_system` database is not included in the repository. Could you please consider adding this file to the repository? This would make it easier for new contributors to set up the database and test their changes.

I'd also like to express my interest in becoming a contributor to this project. I have experience with **PHP, MySQL, and Bootstrap**, and I'd be happy to help with the transition to object-oriented programming. I'm also willing to work on other features and improvements as needed.

Thank you for your consideration!

Best regards,
Milton Vafana

**Comment by TeghSinghJ** [comment]
Hi @nia-cloud-official,

Thank you for your interest in contributing to the Online Chatting System project and for your valuable suggestions!

Regarding the transition to an object-oriented approach, I appreciate your suggestion and agree that it could improve maintainability and scalability. 
I apologize for the missing .sql file. I'll add it to the repository right away to facilitate easier setup and testing for new contributors.

It's great to hear about your experience with PHP, MySQL, and Bootstrap. Your willingness to contribute to the transition and other improvements is highly appreciated. Please feel free to start exploring the code base and propose any specific areas or features you'd like to work on.

Best regards,
Juni Tegh Singh
